/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Inquiry = IDL.Record({
  'age' : IDL.Text,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'medicalIssue' : IDL.Text,
});

export const idlService = IDL.Service({
  'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Inquiry = IDL.Record({
    'age' : IDL.Text,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'medicalIssue' : IDL.Text,
  });
  
  return IDL.Service({
    'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };